Task eight
Archyfly/testguru pull request #10
Opened 2019-08-25 16:13 UTC by Archyfly

2019-08-26 04:38 UTC, BubuntuClu requested changes

2019-08-26 04:38 UTC, BubuntuClu commented on config/routes.rb
> +  resources :answers
этот несурс не нужен отдельно от других

2019-08-26 19:22 UTC, BubuntuClu approved these changes

2019-08-26 19:22 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +<% if success_rate >= 85
что такое 85? не понятно. вынеси это в константу в модели тест пассажа. там же можешь сделать метод `success?` который будет тебе сразу результат это проверки возвращать

2019-08-27 13:17 UTC, Archyfly commented on app/views/test_passages/result.html.erb
> +<% if success_rate >= 85
ok!

2019-08-27 13:43 UTC, Archyfly commented on config/routes.rb
> +  resources :answers
ok

2019-08-27 13:59 UTC, merged