Task eleven
Archyfly/testguru pull request #11
Opened 2019-09-03 14:36 UTC by Archyfly

2019-09-03 18:28 UTC, BubuntuClu requested changes

2019-09-03 18:28 UTC, BubuntuClu commented on app/models/user.rb
> +
где проверка на уникальность?

2019-09-03 18:28 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
вот это и надо вынести в хэлпер флэш сообщений

2019-09-03 18:28 UTC, BubuntuClu commented on app/views/shared/_footer.html.erb
> +    <%= test_flash_helper %>
он пустой, этот хэлпер

2019-09-03 18:28 UTC, BubuntuClu commented on db/migrate/20190828153525_create_users.rb
> +      t.string :email
нельзя менять миграции, которые уже были в мастере. они при деплое не применятся. КРИТИЧНО!

2019-09-03 18:29 UTC, BubuntuClu commented
>С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально

где перенаправление?

2019-09-03 18:29 UTC, BubuntuClu commented
>Используйте объект текущего пользователя при старте прохождения теста

тоже нет

2019-09-04 14:49 UTC, Archyfly commented on app/models/user.rb
> +
added

2019-09-04 15:19 UTC, Archyfly commented on app/views/shared/_footer.html.erb
> +    <%= test_flash_helper %>
ok

2019-09-04 15:20 UTC, Archyfly commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
q

2019-09-10 14:49 UTC, merged