Task fifteen - work with API
Archyfly/testguru pull request #15
Opened 2019-10-01 16:30 UTC by Archyfly

2019-10-01 16:56 UTC, BubuntuClu requested changes

2019-10-01 16:56 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    flash[:alert] = "link_to 'Gist question', #{@created_gist_url}"
почему всегда в алерте отображаться будет?

2019-10-01 16:56 UTC, BubuntuClu commented on lib/clients/git_hub_client.rb
> +class GitHubClient
этот класс уже не нужен

2019-10-01 16:56 UTC, BubuntuClu commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
это уже не надо

2019-10-01 16:56 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    flash[:alert] = "link_to 'Gist question', #{@created_gist_url}"
где привязка к пользователю и вопросу? так же не вижу миграции на создание гиста

2019-10-01 16:56 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    flash[:alert] = "link_to 'Gist question', #{@created_gist_url}"
нет страницы для просмотра созданных гистов
> должна содержать обязательные колонки:
     Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)
     Gist URL. Отображается хэш созданного gist в виде ссылки
     Пользователь. Отображается email пользователя который создал gist

2019-10-15 21:08 UTC, BubuntuClu commented on db/migrate/20191014150327_create_gists.rb
> +     t.string :gisturl
лучше разделить на два слова `gist_url`

2019-10-15 21:09 UTC, BubuntuClu commented
надо конфликты разрулить

2019-10-16 16:42 UTC, BubuntuClu requested changes

2019-10-16 16:42 UTC, BubuntuClu commented on app/views/admin/gists/index.html.erb
> +      <td><%= User.find(gist.user_id).email %></td>
через ассоциации доставай, у тебя ведь есть связь и с пользователем и с вопросом. gist.user.email/gist.question.title
и еще лучше заранее подгрузить их все одним разом, чтобы не делать много вопросов в бд. почитай про `joins/references/eager_load` для AR

2019-10-16 16:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @gist = Gist.new(user_id: current_user.id, question_id: @test_passage.current_question.id, gisturl: @created_gist_url)
создавай через ассоциацию от пользователе гист.

2019-10-16 16:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    gist_to_table
создавать стоит только в случае успеха. в октоките есть метод `last_response`. по его коду можно опредлить было ли успешно создано или нет

2019-10-16 16:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @gist = Gist.new(user_id: current_user.id, question_id: @test_passage.current_question.id, gisturl: @created_gist_url)
зачем тут `@` у `gist`?

2019-10-16 16:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @result = GistQuestionService.new(@test_passage.current_question).call
зачем добавилось `@`?

2019-10-16 17:14 UTC, Archyfly commented on app/views/admin/gists/index.html.erb
> +      <td><%= User.find(gist.user_id).email %></td>
понял, неправильно ассоциации строил, gist.users и gist.questions искал, в модели щапорол косяк с зависимостями, еще, поэтому не получалось, написал топорно, исправлено.

2019-10-16 17:18 UTC, Archyfly commented on app/controllers/test_passages_controller.rb
> +    @gist = Gist.new(user_id: current_user.id, question_id: @test_passage.current_question.id, gisturl: @created_gist_url)
насчет ассоциации от пользователя - current_user же?

2019-10-16 17:37 UTC, Archyfly commented on app/controllers/test_passages_controller.rb
> +    gist_to_table
last response - 

131 132 133 | # File 'lib/octokit/connection.rb', line 131  
def last_response   
@last_response if defined? @last_response
end
-- | --
он же возвращает ответ - у нас же для этого задуман result ?

2019-10-16 17:48 UTC, merged

2019-10-16 18:19 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @gist = Gist.new(user_id: current_user.id, question_id: @test_passage.current_question.id, gisturl: @created_gist_url)
да

2019-10-16 18:21 UTC, BubuntuClu commented on app/models/test.rb
> +  accepts_nested_attributes_for :questions
а это зачем?

2019-10-16 18:21 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    gist_to_table if result
у тебя два if по одному условию. надо бы их объединить

2019-10-16 18:22 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    gist_to_table
резалт просто результат клиента возвращает