Task twenty
Archyfly/testguru pull request #24
Opened 2019-11-14 17:36 UTC by Archyfly

2019-11-14 21:58 UTC, BubuntuClu requested changes

2019-11-14 21:58 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +     @test_passage.update(is_finished: true)
не,не,не. никакой логики во вьюхе, причем такой, что объект меняет. вычисления еще куда ни шло. но это точно нет. это надо делать в контроллере/моделе

2019-11-14 21:58 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +  <td><%= test.test_passages.pluck(:is_finished).count %></td>
а зачем делать плак, если ты считаешь количество? почему объекты не посчитать? может ты забыл еще уникальность или nil отсеять?

2019-11-15 00:20 UTC, Archyfly commented on app/views/tests/_test.html.erb
> +  <td><%= test.test_passages.pluck(:is_finished).count %></td>
Не перенес еще. Там у меня получается коллекция объектов

2019-11-15 02:39 UTC, merged