Task five
Archyfly/testguru pull request #5
Opened 2019-07-23 17:45 UTC by Archyfly

2019-07-24 05:50 UTC, BubuntuClu requested changes

2019-07-24 05:50 UTC, BubuntuClu commented on db/schema.rb
> -    t.boolean "correct", default: false
куда ушел столбец? он нужен

2019-07-24 05:50 UTC, BubuntuClu commented on app/models/answer.rb
> +  scope :is_true, -> { where("correct = 1")}
`correct`  у тебя типа булеан. `where(correct: true)`. лучше так и назвать ассоциацию `correct`

2019-07-24 05:50 UTC, BubuntuClu commented on app/models/category.rb
> +  scope :view_title_asc, -> { pluck("title").order('title ASC')}
просто `order` и это должен быть дефолтный скоуп, а не обычный

2019-07-24 05:50 UTC, BubuntuClu commented on app/models/question.rb
> +  def valid_count
эта валидация должна быть в моделе ответов, потому что вопрос ты создал и на момент создания будет проверка и в вопросе будет 0 ответов. причем валидация не пройдет из-за плохого условия

2019-07-24 05:50 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :levels, -> { pluck('title', 'level') }
не надо помещать выборку в скоупы, я тебе про это уже писал. должен возвращаться объект ActiveRecord::Relation для возможности создания цепочки вызовов

2019-07-24 05:50 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"}
нужно добавить составной уникальный индекс в БД

2019-07-24 17:05 UTC, Archyfly commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"}
Добавлено

2019-07-24 17:12 UTC, Archyfly commented on app/models/category.rb
> +  scope :view_title_asc, -> { pluck("title").order('title ASC')}
учел, изменил

2019-07-24 17:15 UTC, Archyfly commented on app/models/answer.rb
> +  scope :is_true, -> { where("correct = 1")}
переименовано

2019-07-24 17:19 UTC, Archyfly commented on db/schema.rb
> -    t.boolean "correct", default: false
Вчера миграции откатывал, пошел по сложному пути, дропнул таблицу. добавлено.

2019-07-25 04:38 UTC, BubuntuClu approved these changes

2019-07-25 04:38 UTC, BubuntuClu commented on app/models/answer.rb
> +    puts question.answers.count
отладочную информацию можно удалить

2019-07-25 04:38 UTC, BubuntuClu commented on app/models/test.rb
> +  #validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"}заменил на ключ в базе
это тоже надо. ограничения должны дублироваться и в приложении и в БД

2019-07-26 14:34 UTC, merged