Task six
Archyfly/testguru pull request #6
Opened 2019-07-29 04:36 UTC by Archyfly

Проверьте пожалуйста.
Вроде связь в routes есть для tests/questions/ - но так же как в уроке метод new не отрабатывается, что не так сделал?

2019-07-29 05:15 UTC, BubuntuClu requested changes

2019-07-29 05:15 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +  <p>
это не надо, `test_id` в url передается

2019-07-29 05:15 UTC, BubuntuClu commented on config/routes.rb
> +
все что ниже этой строчки не надо

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id)
`author_id` тут не нужен.
найди пользователя. сейчас можно сделать просто `User.first`

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
`user.authored_tests.new(test_params)`
так же не забывай что данные могут не валидные
`if test.save` надо делать

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
`create` и `save` оба делают запросы в БД. смысла нет в `save` сразу после `create`
```
question = @test.questions.new(questions_params)
if question.save
  ...
else
 ...
end
```

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :test_id)
`test_id` тут не надо

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def find_question
где используется этот метод?

2019-07-29 05:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +
где обратный вызов для поиска теста?

2019-07-29 05:27 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/question" method="post">
тут должно быть примерно так
`<form action="/tests/<%= @test.id %>/questions" method="post">`
можно из переменной брать или из `params` значение id теста

2019-08-01 06:17 UTC, BubuntuClu requested changes

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +        @question.update_attributes!(question_params)
1 - тут у тебя будет ошибка. откуда берется `@question`?
2 - используй просто `update`. `@questions.update(questions_params)`

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +
где экшен удаления?

2019-08-01 06:17 UTC, BubuntuClu commented on app/models/test.rb
> +  #validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"} # заменил на ключ в базе
это надо оставить

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  def start
а этот метод откуда тут?

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def find_test
это излишний метод, ты это можешь получить напрямую из `params` или из `@test`

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> + before_action :set_test#, only: %i[create]
этот экшен не нужен

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +before_action :find_question, only: %i[show]
тебе нахождение вопроса понадобиться в нескольких экшенах. сейчас из-за этого есть одна ошибка

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +
>Напишите обработку исключения для случая когда вопрос не был найден

это не реализовано

2019-08-01 06:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question_new = @test.questions.create!(question_params)
1 - нельзя использовать бэнг-методы(!) без блока `rescue`, если у тебя невалидные параметры, будет райзится исключение, а ты его не обрабатываешь
2 - нет смысла делать `create`, а затем `save`. используя `create`, ты уже в БД сохранил запись.
`question_new = @test.questions.new(question_params)`

2019-08-01 17:31 UTC, Archyfly commented on app/models/test.rb
> +  #validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"} # заменил на ключ в базе
ok

2019-08-01 17:34 UTC, Archyfly commented on app/controllers/questions_controller.rb
> + before_action :set_test#, only: %i[create]
опять все сломалось, ну как то

2019-08-01 18:09 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +    question_new = @test.questions.create!(question_params)
ok

2019-08-02 14:14 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +before_action :find_question, only: %i[show]
не понятно

2019-08-02 14:15 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +  def find_test
ок

2019-08-02 14:15 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +  def start
Из скринкаста, проба, смотрел, не убрал :(

2019-08-02 14:16 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +
добавлено

2019-08-02 14:17 UTC, Archyfly commented on app/views/questions/new.html.erb
> +<form action="/question" method="post">
ок

2019-08-02 14:17 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
исправлено

2019-08-02 14:18 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
переделано

2019-08-03 17:27 UTC, BubuntuClu approved these changes

2019-08-03 17:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
у тебя есть `find_question`, зачем ты еще раз ищешь вопрос?

2019-08-03 17:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    begin
просто `rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found` после `before_action`

реализация метода 
```
def rescue_with_question_not_found
    render plain: "404. Question not found!"
  end
```

2019-08-03 17:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if question_new.save
```
if question.save
  redirect_to question
else
 render :new
end
```

2019-08-03 17:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
не заметил что бы было переделано, но все равно тут через `new/save` надо сделать для защиты

2019-08-03 17:27 UTC, BubuntuClu commented on config/routes.rb
> +  resources :tests, shallow: true do
для верхнего уровня ресурсов смысла нет `shallow`

2019-08-05 15:59 UTC, merged