Task seven
Archyfly/testguru pull request #7
Opened 2019-08-09 17:37 UTC by Archyfly

task seven, helpers, views, partials

2019-08-09 18:15 UTC, BubuntuClu requested changes

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find_by(params[:id])
было правильно. когда используешь find_by надо указать поле

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>  before_action :find_question #, only: %i[show]
у тебя это будет падать на методах index,new

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +before_action :set_test #, only: %i[create]
тест тебе тоже не везде нужен.

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def index
этот метод не нужен. ты вопросы выводишь на странице теста

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id])
у тебя есть `find_question`

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.new
относительно теста создавай

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
`find_question` у тебя есть. зачем еще раз находить?

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @category = Category.find(params[:id])
что за id сюда подставляется?  у тебя тут только один параметр, это ID теста

2019-08-09 18:15 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @author = User.find(params[:id])
что за id сюда подставляется?  у тебя тут только один параметр, это ID теста

2019-08-13 05:06 UTC, BubuntuClu requested changes

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    find_question
у тебя есть строка
`before_action :find_question, only: %i[show, edit, destroy]`
что она означает? то, что до вызова методов `show, edit, destroy` будет вызван и выполнен метод `find_question`. зачем внутри `show` ты еще раз его вызываешь? он у тебя уже выполнен и все его переменные тебе уже доступны. то есть у тебя уже есть `@question`

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    find_question
тоже самое

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    find_question
тебе точно понятно как работает `before_action`? в прошлом ПРе у тебя тоже с ним были проблемы

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      @question = Question.find(params[:id])
вот тут о5 ты ищешь вопрос, когда у тебя `before_action :find_question, only: %i[show, edit, destroy]`

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def index
метод не удалил

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
before_action :find_test, only: %i[edit, update, show]

2019-08-13 05:06 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>      @test = Test.find(params[:id])
before_action :find_test, only: %i[edit, update, show]

2019-08-13 05:06 UTC, BubuntuClu commented on app/views/questions/index.html.erb
эта вьюха не нужна

2019-08-13 05:06 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<p>
отступы

2019-08-13 05:06 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<%= @questions.each do |q| %>
тут можно использовать `render @questions`

2019-08-14 20:00 UTC, BubuntuClu requested changes

2019-08-14 20:00 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header
вообще предполагалось что-то такое
```
def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end
```
что ты один хелпер будешь использовать для заголовока, а не просто поместить туда строку для определения названия теста

2019-08-14 20:00 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
тут не исправил

2019-08-14 20:00 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>      @test = Test.find(params[:id])
и тут не исправил

2019-08-14 20:00 UTC, BubuntuClu commented on app/views/shared/_footer.html.erb
> +    <%= Time.now.year %></h5>
вот это надо вынести в хэлпер

2019-08-14 20:00 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    @tests.count
1 - количество вопросов
2 - можно и без хэлпера, просто на странице теста `@test.questions.count`

2019-08-14 20:01 UTC, BubuntuClu commented
>Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

вот это еще надо

2019-08-15 17:15 UTC, Archyfly commented on app/helpers/tests_helper.rb
> +    @tests.count
ok

2019-08-15 17:19 UTC, Archyfly commented on app/views/shared/_footer.html.erb
> +    <%= Time.now.year %></h5>
ok, дообавил в application_helper

2019-08-15 17:32 UTC, Archyfly commented on app/helpers/questions_helper.rb
> +  def question_header
Спасибо!!!

2019-08-15 17:33 UTC, Archyfly commented on app/views/tests/show.html.erb
> +<p>
ок

2019-08-15 17:35 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
ok

2019-08-15 17:35 UTC, Archyfly commented on app/controllers/tests_controller.rb
>      @test = Test.find(params[:id])
ok

2019-08-15 17:36 UTC, Archyfly commented on app/controllers/questions_controller.rb
>      @question = Question.find(params[:id])
ok

2019-08-15 17:36 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +    find_question
ok

2019-08-15 17:37 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +    @category = Category.find(params[:id])
ok

2019-08-15 19:49 UTC, BubuntuClu approved these changes

2019-08-15 19:49 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    #@question = Question.find(params[:id])
удаляй комментарии сразу, не надо их в коде держать

2019-08-15 19:49 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @questions.count
это тут зачем? ты это никак не используешь

2019-08-15 19:49 UTC, BubuntuClu commented on app/models/test.rb
> +  #validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"} # заменил на ключ в базе
это надо оставить

2019-08-15 19:49 UTC, BubuntuClu commented on app/views/questions/index.html.erb
не удалил, как и метод в контроллере

2019-08-15 19:49 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1> <%= question_header(@question) %> </h1>
ты это можешь вынести в паршиал `form`

2019-08-15 19:49 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<h1> <%= question_header(@question) %></h1>
вынеси это тоже в паршиал

2019-08-15 19:49 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<%= @questions.each do |q| %>
`=render @questions`

2019-08-16 17:09 UTC, Archyfly commented on app/views/tests/show.html.erb
> +<%= @questions.each do |q| %>
ok

2019-08-16 17:11 UTC, Archyfly commented on app/views/questions/new.html.erb
> +<h1> <%= question_header(@question) %></h1>
ok

2019-08-16 17:11 UTC, Archyfly commented on app/views/questions/edit.html.erb
> +<h1> <%= question_header(@question) %> </h1>
ok

2019-08-16 17:12 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +    @questions.count
ok

2019-08-16 17:12 UTC, Archyfly commented on app/controllers/questions_controller.rb
> +    #@question = Question.find(params[:id])
ok

2019-08-19 15:42 UTC, Archyfly commented on app/controllers/tests_controller.rb
> +    @author = User.find(params[:id])
ok

2019-08-19 15:44 UTC, merged